### ISSUE TITLE
Error: block.nvim/lua/block/block.lua:129: attempt to index a nil value

### ISSUE THREAD

**Issue by nyngwang** [HampusHauffman/block.nvim#10]
I have a chance to get the following error after calling `:e` at a buffer with the highlighting of `:BlockOn` has been applied.

```
Error executing vim.schedule lua callback: ...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:129: attempt to index a nil value
stack traceback:
	...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:129: in function 'update'
	...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:152: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by gennaro-tedesco** [comment]
> It will still be great if you could try my PR and let me know the result :)

I will test it as I finish work (in one hour or so) :)

**Comment by gennaro-tedesco** [comment]
I tested your PR and all works fine except when using [treesitter-objects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) with the [lsp interop](https://github.com/nvim-treesitter/nvim-treesitter-textobjects#textobjects-lsp-interop) preview windows (with that preview window the exception is still generated). I will try to go through the code later with some more time to better understand if there are other conditions that may trigger it.

**Comment by HampusHauffman** [comment]
> I too am seeing the same error, in particular when opening a floating window (whether it is a fuzzy finder, a diagnostic or other types of floating objects); for line 152 I see the stacktrace to be
> 
> ```lua
> 	...ro/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:129: in function 'update'
> 	...ro/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:152: in function 'fn'
> 	vim/_editor.lua:556: in function 'cb'
> 	vim/_editor.lua:324: in function <vim/_editor.lua:323>
> ```
> 
> (not sure if your PR covers this case too)

Curious...
```lua
    local success, parser = pcall(ts.get_parser, bufnr)
```
Should take care of cases where treesitter cant find a parser

**Comment by HampusHauffman** [comment]
@gennaro-tedesco 
Could you try out
https://github.com/HampusHauffman/block.nvim/pull/14

@nyngwang 
A lot is happening in your PR.
Lets see if this fixes the initial issue :)

**Comment by HampusHauffman** [comment]
https://github.com/HampusHauffman/block.nvim/pull/14

**Comment by nyngwang** [comment]
@HampusHauffman Yes, I forgot to switch to a new branch, lol. Thanks for the redo. Now I just need to create one new PR for #4

**Comment by gennaro-tedesco** [comment]
> @gennaro-tedesco Could you try out #14

All issues seem to be fixed _except_ again for lsp-interop floating window of treesitter-objects 🤔

**Comment by nyngwang** [comment]
@gennaro-tedesco Can you post the error message again? I can check this for you.

**Comment by gennaro-tedesco** [comment]
The full error message I get is the following:
```lua
Error executing vim.schedule lua callback: ...ro/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:129: attempt to index a nil value
stack traceback:
	...ro/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:129: in function 'update'
	...ro/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:152: in function 'fn'
	vim/_editor.lua:556: in function 'cb'
	vim/_editor.lua:324: in function <vim/_editor.lua:323>
```

**Comment by HampusHauffman** [comment]
Closing this for now. 
thank you @gennaro-tedesco  and @nyngwang
