### ISSUE TITLE
Incorrect coloring in several cases

### ISSUE THREAD

**Issue by nyngwang** [HampusHauffman/block.nvim#12]
## Case 1

In Lua, using `..` to concatenate strings will create a new level, but it shouldn't:

<img src="https://github.com/HampusHauffman/block.nvim/assets/24765272/79e92a68-be16-423b-bf4d-88814afedc86" width="500">

## Case 2

Using nerd-font symbols(probably related to Unicode? which will make solving this problem hard) will make the calculation incorrect, so there will be some "black boxes/rectangles" like this:

<img src="https://github.com/HampusHauffman/block.nvim/assets/24765272/a843e566-78f0-4bbd-829b-3e84e5aff7e6" width="500">

If I further scroll horizontally, then this second case is basically issue #4, i.e. those "black boxes" got wider.

<img src="https://github.com/HampusHauffman/block.nvim/assets/24765272/e5e3894d-462c-41c5-b4d3-ffb9daf28c56" width="500">

**Comment by Keymo42** [comment]
Coloring also seems to be wrong for go code in general.
I wonder if it would be possible to use the same indent information that Treesitter uses for folds.
