### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by 7ColorsCat** [HampusHauffman/block.nvim#18]
![2023-06-16_10-20](https://github.com/HampusHauffman/block.nvim/assets/43630437/bcfa603e-e7b1-4eb0-aecc-60d09e3bff8f)
 
 try and get this error

**Comment by gennaro-tedesco** [comment]
Most likely a duplicate of #10

**Comment by HampusHauffman** [comment]
Yep. Should be fixed now.
