### ISSUE TITLE
virt_text_pos="inline" not supported in 9.0

### ISSUE THREAD

**Issue by MLFlexer** [HampusHauffman/block.nvim#2]
I have version 9.0, which do not support virt_text_pos="inline", which is used here: https://github.com/HampusHauffman/block.nvim/blob/c2f5141226870c2a64a2a76da79209f2abcb95a8/lua/block/block.lua#LL82C13-L82C37

So I get an error whenever I try to enable the plugin.

If the virt_text_pos="inline" is a requirement for the plugin to work, then it might only work on the nightly release or whenever the 10.x release is out?

**Comment by HampusHauffman** [comment]
https://github.com/HampusHauffman/block.nvim/commit/e67d91e16420379f941eb23449f8cc6854b92e45
