### ISSUE TITLE
Nothing works: the only effect on :Block is that cursor line disappears

### ISSUE THREAD

**Issue by D00mch** [HampusHauffman/block.nvim#20]
Tried on Typescript, Fennel, Clojure, and Dart (below):

https://github.com/HampusHauffman/block.nvim/assets/14236531/84df3696-2525-47ea-9fc9-c0120ad25ac2

I tried changing theme, opening it in Terminal and in Neovide, setting vim.opt.termguicolors to false/true.

**Comment by HampusHauffman** [comment]
Could you share your setup. And also print out what the highlight ”bloc0” is set to?

**Comment by HampusHauffman** [comment]
Closing this as no answer was given to previous question
