### ISSUE TITLE
not loading with packer

### ISSUE THREAD

**Issue by timon-sue** [HampusHauffman/block.nvim#25]
```	
use {
  "HampusHauffman/block.nvim",
  config = function()
    require("block").setup({})
  end
}
use {
  'nvim-treesitter/nvim-treesitter',
  run = ':TSUpdate'
}
```
`:PackerUpdate` doesn't show any issues but `:PackerStatus` doesn't show the plugin loaded and `:Block` is not available.

**Comment by HampusHauffman** [comment]
block.nvim requires treesitter.
The issue might be treesitter is loaded after block.
try adding 

requires = {'nvim-treesitter/nvim-treesitter'}

Should maybe be clearer in the docs, Lazy.nvim  loads packages in order automatically but not packer as far as i'm aware.
