### ISSUE TITLE
block.lua:41: attempt to call field 'unpack' (a nil value)

### ISSUE THREAD

**Issue by nyngwang** [HampusHauffman/block.nvim#3]
```
Error executing Lua callback: ...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:41: attempt to call field 'unpack' (a nil value)
stack traceback:
	...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:41: in function 'convert_ts_node'
	...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:138: in function 'update'
	...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:147: in function 'add_buff_and_start'
	...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:165: in function <...ng/.local/share/nvim/lazy/block.nvim/lua/block/block.lua:162>
```

```lua
use {
  'HampusHauffman/block.nvim',
  config = function ()
    require('block').setup {
      percent = 0.8, -- e.g. 0.8 would change each box to be 20% darker than the last and 1.2 would be 20% brighter.
      depth = 4, -- after this the colors reset.
      automatic = false,
    }
  end
}
```

**Comment by chrisgrieser** [comment]
also got this error, also using default settings

**Comment by HampusHauffman** [comment]
Do you have Treesitter installed for the filetype you're opening?

**Comment by HampusHauffman** [comment]
https://github.com/HampusHauffman/block.nvim/commit/6c5b0e13fdfe7ae0b97accb52274066e8ccb7a88
Curious if this was the issue.
If you could please try it again after updating.
Mind you calling Block on files types that are not supported or not installed with treesitter wont work (but shouldnt throw an error)

**Comment by chrisgrieser** [comment]
using on lua files, where I also have the treesitter parser installed

still getting the very same error with the update

**Comment by OneSleeve** [comment]
Running into the same issue.

**Comment by IndianBoy42** [comment]
This is not a treesitter problem or related to that commit, *as the error says* there is no `table.unpack` on your systems. `table.unpack and table.pack` were added in lua 5.2 moving it from builtin functions to inside the `table` metatable. luajit is based on lua 5.1, with some 5.2 additions backported. If luajit is compiled with [LUAJIT_ENABLE_LUA52COMPAT](https://luajit.org/extensions.html) it enables a few more 5.2 features, among which is `table.unpack` and `table.pack` in addition to the builtins `unpack, pack`. It seems some people have it and some don't 

Anyway just use `unpack, pack`

**Comment by OneSleeve** [comment]
Thank you!

Changing `table.unpack` to `unpack` worked.

**Comment by chrisgrieser** [comment]
nice, thanks @IndianBoy42.

btw @HampusHauffman, you can catch this type of problem early on by telling the lua-lsp to use `LuaJIT`.

create a file named `.luarc.json` with the following content and put it into the root folder of your plugin.
```lua
{
	"runtime.version": "LuaJIT"
}
```

Then, using lua code not valid in LuaJIT like `table.unpack` should result in a diagnostic message by the lua LSP:
![CleanShot 2023-06-15 at 13 14 35@2x](https://github.com/HampusHauffman/block.nvim/assets/73286100/8752c2a0-52c8-42f9-8087-ef4cb91501b7)

**Comment by nyngwang** [comment]
While the error disappeared, it doesn't show me the highlight after calling `:BlockOn`.

**Comment by HampusHauffman** [comment]
@nyngwang Hard to troubleshoot if just nothing happens :/

**Comment by nyngwang** [comment]
@HampusHauffman I just found a clue that if I call the `setup` the second time manually after the Lua LSP has been loaded then calling `:Block` again will show the coloring.

**Comment by HampusHauffman** [comment]
@nyngwang Could you show me the setup you have in your plugin manager?

**Comment by nyngwang** [comment]
Yes, I'm using the same one:

```lua
use {
  'HampusHauffman/block.nvim',
  config = function ()
    require('block').setup {
      percent = 0.8, -- e.g. 0.8 would change each box to be 20% darker than the last and 1.2 would be 20% brighter.
      depth = 4, -- after this the colors reset.
      automatic = false,
    }
  end
}
```

**Comment by HampusHauffman** [comment]
@nyngwang Does that mean you solved it?

**Comment by nyngwang** [comment]
No. I'm still finding the reason why I need to call the `setup` again to ensure that `:BlockOn` will take effect after entering Neovim. But I found that I don't have to wait the Lua LSP to finish before calling `setup`.
