### ISSUE TITLE
Extarks scroll with horizontal scroll.

### ISSUE THREAD

**Issue by HampusHauffman** [HampusHauffman/block.nvim#4]
Currently i've not been able to figure out a way to manage horizontal scroll when `opt.wrap = false`.
Any suggestions for how to fix this is:o
<img width="993" alt="Screenshot 2023-06-15 at 13 07 02" src="https://github.com/HampusHauffman/block.nvim/assets/3845743/5897ee3d-f4e2-4027-bbeb-e61d2bf83e7f">
Resulting in this ugly mess on long lines.
Any idea on how to fix this is greatly appreciated!

**Comment by HampusHauffman** [comment]
> Also noticed this issue. I guess we need to refresh/recalculate the extmark on `WinScrolled`, which includes scrolling horizontally.

The issue is that i've yet to find a way to see how far right you've scrolled :/

**Comment by nyngwang** [comment]
@HampusHauffman Good news, I just fixed it :) (I spend probably 3 hours lol)

**Comment by HampusHauffman** [comment]
@nyngwang if you have the time could you test out #22 :)

**Comment by nyngwang** [comment]
Did. It's safe to close this issue now~
