### ISSUE TITLE
Feature: outline mode

### ISSUE THREAD

**Issue by tzachar** [HampusHauffman/block.nvim#9]
Would you consider adding support for outline mode? something similar to [blockman](https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman)?

Also, only triggering for the current block would be awesome.

**Comment by HampusHauffman** [comment]
Only trigger for current block would be a fun feature and i think not to hard to do.
The border would not be possible without adding "new" lines above and below blocks. Neovim cant combine symbols so havin a line above a character would need a new line entierly

**Comment by tzachar** [comment]
This might be achieved with something similar to underlines, which modern terminal emulators support.
